### ISSUE TITLE
socket.readline导致maybe in an endless loop

### ISSUE THREAD

**Issue by lqflyc** [yyl-20020115/WinSkynet#2]
lreadline函数中的readinput_node第二个参数传入的是0，导致在readinput的_read函数读取时阻塞掉
实际上lreadline函数不需要加上readinput_node，socket是非阻塞模式，底层有数据发送过来时，会触发socket的协程读取数据并进行后续处理，因此我建议把readinput_node调用的地方注释掉也不影响整个框架运行。

**Comment by yyl-20020115** [comment]
因为只是移植，不是特别清楚原作者的想法。我感觉去掉也不会有什么太大的影响，但若作者确实需要从stdin读取输入，可能就得留下了。这个是lua的lib，到底skynet要怎么用它，我并不是特别清楚。为保险起见，我暂时就不动它了，同时感谢建议。
